require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7

Layout/LineLength:
  Max: 100

Metrics/BlockLength:
  Exclude:
    - quick_and_ruby.gemspec
    - spec/**/*.rb

Metrics/MethodLength:
  Max: 25

# Style/StringLiterals:
#   Enabled: true
#   EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

# RSpec

RSpec/MultipleExpectations:
  Max: 2
