AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6


Layout/LineLength:
  Max: 100

Metrics/BlockLength:
  Exclude:
    - quick_and_ruby.gemspec
    - spec/**/*.rb

Metrics/MethodLength:
  Max: 25

# Style/StringLiterals:
#   Enabled: true
#   EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes
